<?php

namespace Database\Seeders;

use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;

class CombinacaoSeeder extends Seeder
{
    /**
     * Run the database seeds.
     */
    public function run(): void
    {
        DB::table('combinacoes')->insert([            
            [
                "codigo" => "USD-BRL",
                "codigo_moeda_base" => "USD",
                "descricao" => "Dólar Americano/Real Brasileiro",
                "created_at" => now(),
                "updated_at" => now(),
            ],
            [
                "codigo" => "USD-BRLT", 
                "codigo_moeda_base" => "USD",
                "descricao" => "Dólar Americano/Real Brasileiro Turismo",
                "created_at" => now(),
                "updated_at" => now(),
            ],
            [
                "codigo" => "CAD-BRL", 
                "codigo_moeda_base" => "CAD",
                "descricao" => "Dólar Canadense/Real Brasileiro",
                "created_at" => now(),
                "updated_at" => now(),
            ],
            [
                "codigo" => "EUR-BRL", 
                "codigo_moeda_base" => "EUR",
                "descricao" => "Euro/Real Brasileiro",
                "created_at" => now(),
                "updated_at" => now(),
            ],
            [
                "codigo" => "GBP-BRL", 
                "codigo_moeda_base" => "GBP",
                "descricao" => "Libra Esterlina/Real Brasileiro",
                "created_at" => now(),
                "updated_at" => now(),
            ],
            [
                "codigo" => "ARS-BRL", 
                "codigo_moeda_base" => "ARS",
                "descricao" => "Peso Argentino/Real Brasileiro",
                "created_at" => now(),
                "updated_at" => now(),
            ],
            [
                "codigo" => "BTC-BRL", 
                "codigo_moeda_base" => "BTC",
                "descricao" => "Bitcoin/Real Brasileiro",
                "created_at" => now(),
                "updated_at" => now(),
            ],
            [
                "codigo" => "LTC-BRL", 
                "codigo_moeda_base" => "LTC",
                "descricao" => "Litecoin/Real Brasileiro",
                "created_at" => now(),
                "updated_at" => now(),
            ],
            [
                "codigo" => "JPY-BRL", 
                "codigo_moeda_base" => "JPY",
                "descricao" => "Iene Japonês/Real Brasileiro",
                "created_at" => now(),
                "updated_at" => now(),
            ],
            [
                "codigo" => "CHF-BRL", 
                "codigo_moeda_base" => "CHF",
                "descricao" => "Franco Suíço/Real Brasileiro",
                "created_at" => now(),
                "updated_at" => now(),
            ],
            [
                "codigo" => "AUD-BRL", 
                "codigo_moeda_base" => "AUD",
                "descricao" => "Dólar Australiano/Real Brasileiro",
                "created_at" => now(),
                "updated_at" => now(),
            ],
            [
                "codigo" => "CNY-BRL", 
                "codigo_moeda_base" => "CNY",
                "descricao" => "Yuan Chinês/Real Brasileiro",
                "created_at" => now(),
                "updated_at" => now(),
            ],
            [
                "codigo" => "ILS-BRL", 
                "codigo_moeda_base" => "ILS",
                "descricao" => "Novo Shekel Israelense/Real Brasileiro",
                "created_at" => now(),
                "updated_at" => now(),
            ],
            [
                "codigo" => "ETH-BRL", 
                "codigo_moeda_base" => "ETH",
                "descricao" => "Ethereum/Real Brasileiro",
                "created_at" => now(),
                "updated_at" => now(),
            ],
            [
                "codigo" => "XRP-BRL", 
                "codigo_moeda_base" => "XRP",
                "descricao" => "XRP/Real Brasileiro",
                "created_at" => now(),
                "updated_at" => now(),
            ],
            [
                "codigo" => "DOGE-BRL", 
                "codigo_moeda_base" => "DOGE",
                "descricao" => "Dogecoin/Real Brasileiro",
                "created_at" => now(),
                "updated_at" => now(),
            ],
            [
                "codigo" => "SGD-BRL", 
                "codigo_moeda_base" => "SGD",
                "descricao" => "Dólar de Cingapura/Real Brasileiro",
                "created_at" => now(),
                "updated_at" => now(),
            ],
            [
                "codigo" => "AED-BRL", 
                "codigo_moeda_base" => "AED",
                "descricao" => "Dirham dos Emirados/Real Brasileiro",
                "created_at" => now(),
                "updated_at" => now(),
            ],
            [
                "codigo" => "DKK-BRL", 
                "codigo_moeda_base" => "DKK",
                "descricao" => "Coroa Dinamarquesa/Real Brasileiro",
                "created_at" => now(),
                "updated_at" => now(),
            ],
            [
                "codigo" => "HKD-BRL", 
                "codigo_moeda_base" => "HKD",
                "descricao" => "Dólar de Hong Kong/Real Brasileiro",
                "created_at" => now(),
                "updated_at" => now(),
            ],
            [
                "codigo" => "MXN-BRL", 
                "codigo_moeda_base" => "MXN",
                "descricao" => "Peso Mexicano/Real Brasileiro",
                "created_at" => now(),
                "updated_at" => now(),
            ],
            [
                "codigo" => "NOK-BRL", 
                "codigo_moeda_base" => "NOK",
                "descricao" => "Coroa Norueguesa/Real Brasileiro",
                "created_at" => now(),
                "updated_at" => now(),
            ],
            [
                "codigo" => "NZD-BRL", 
                "codigo_moeda_base" => "NZD",
                "descricao" => "Dólar Neozelandês/Real Brasileiro",
                "created_at" => now(),
                "updated_at" => now(),
            ],
            [
                "codigo" => "PLN-BRL", 
                "codigo_moeda_base" => "PLN",
                "descricao" => "Zlóti Polonês/Real Brasileiro",
                "created_at" => now(),
                "updated_at" => now(),
            ],
            [
                "codigo" => "SAR-BRL", 
                "codigo_moeda_base" => "SAR",
                "descricao" => "Riyal Saudita/Real Brasileiro",
                "created_at" => now(),
                "updated_at" => now(),
            ],
            [
                "codigo" => "SEK-BRL", 
                "codigo_moeda_base" => "SEK",
                "descricao" => "Coroa Sueca/Real Brasileiro",
                "created_at" => now(),
                "updated_at" => now(),
            ],
            [
                "codigo" => "THB-BRL", 
                "codigo_moeda_base" => "THB",
                "descricao" => "Baht Tailandês/Real Brasileiro",
                "created_at" => now(),
                "updated_at" => now(),
            ],
            [
                "codigo" => "TRY-BRL", 
                "codigo_moeda_base" => "TRY",
                "descricao" => "Nova Lira Turca/Real Brasileiro",
                "created_at" => now(),
                "updated_at" => now(),
            ],
            [
                "codigo" => "TWD-BRL", 
                "codigo_moeda_base" => "TWD",
                "descricao" => "Dólar Taiuanês/Real Brasileiro",
                "created_at" => now(),
                "updated_at" => now(),
            ],
            [
                "codigo" => "VEF-BRL", 
                "codigo_moeda_base" => "VEF",
                "descricao" => "Bolívar Venezuelano/Real Brasileiro",
                "created_at" => now(),
                "updated_at" => now(),
            ],
            [
                "codigo" => "ZAR-BRL", 
                "codigo_moeda_base" => "ZAR",
                "descricao" => "Rand Sul-Africano/Real Brasileiro",
                "created_at" => now(),
                "updated_at" => now(),
            ],
            [
                "codigo" => "CLP-BRL", 
                "codigo_moeda_base" => "CLP",
                "descricao" => "Peso Chileno/Real Brasileiro",
                "created_at" => now(),
                "updated_at" => now(),
            ],
            [
                "codigo" => "PYG-BRL", 
                "codigo_moeda_base" => "PYG",
                "descricao" => "Guarani Paraguaio/Real Brasileiro",
                "created_at" => now(),
                "updated_at" => now(),
            ],
            [
                "codigo" => "UYU-BRL", 
                "codigo_moeda_base" => "UYU",
                "descricao" => "Peso Uruguaio/Real Brasileiro",
                "created_at" => now(),
                "updated_at" => now(),
            ],
            [
                "codigo" => "COP-BRL", 
                "codigo_moeda_base" => "COP",
                "descricao" => "Peso Colombiano/Real Brasileiro",
                "created_at" => now(),
                "updated_at" => now(),
            ],
            [
                "codigo" => "PEN-BRL", 
                "codigo_moeda_base" => "PEN",
                "descricao" => "Sol do Peru/Real Brasileiro",
                "created_at" => now(),
                "updated_at" => now(),
            ],
            [
                "codigo" => "BOB-BRL", 
                "codigo_moeda_base" => "BOB",
                "descricao" => "Boliviano/Real Brasileiro",
                "created_at" => now(),
                "updated_at" => now(),
            ],
            [
                "codigo" => "RUB-BRL", 
                "codigo_moeda_base" => "RUB",
                "descricao" => "Rublo Russo/Real Brasileiro",
                "created_at" => now(),
                "updated_at" => now(),
            ],
            [
                "codigo" => "INR-BRL", 
                "codigo_moeda_base" => "INR",
                "descricao" => "Rúpia Indiana/Real Brasileiro",
                "created_at" => now(),
                "updated_at" => now(),
            ],
            [
                "codigo" => "USD-BRLPTAX", 
                "codigo_moeda_base" => "USD",
                "descricao" => "Dólar Americano/Real Brasileiro",
                "created_at" => now(),
                "updated_at" => now(),
            ],
            [
                "codigo" => "XAU-BRL", 
                "codigo_moeda_base" => "XAU",
                "descricao" => "Ouro/Real Brasileiro",
                "created_at" => now(),
                "updated_at" => now(),
            ],
            [
                "codigo" => "XAG-BRL", 
                "codigo_moeda_base" => "XAG",
                "descricao" => "Prata Spot/Real Brasileiro",
                "created_at" => now(),
                "updated_at" => now(),
            ],
            [
                "codigo" => "RSD-BRL", 
                "codigo_moeda_base" => "RSD",
                "descricao" => "Dinar Sérvio/Real Brasileiro",
                "created_at" => now(),
                "updated_at" => now(),
            ],
            [
                "codigo" => "KRW-BRL", 
                "codigo_moeda_base" => "KRW",
                "descricao" => "Won Sul-Coreano/Real Brasileiro",
                "created_at" => now(),
                "updated_at" => now(),
            ],
            [
                "codigo" => "BRETT-BRL", 
                "codigo_moeda_base" => "BRETT",
                "descricao" => "Brett/Real Brasileiro",
                "created_at" => now(),
                "updated_at" => now(),
            ],
            [
                "codigo" => "SOL-BRL", 
                "codigo_moeda_base" => "SOL",
                "descricao" => "Solana/Real Brasileiro",
                "created_at" => now(),
                "updated_at" => now(),
            ],
            [
                "codigo" => "BNB-BRL", 
                "codigo_moeda_base" => "BNB",
                "descricao" => "Binance Coin/Real Brasileiro",
                "created_at" => now(),
                "updated_at" => now(),
            ],
            [
                "codigo" => "EUR-BRLT", 
                "codigo_moeda_base" => "EUR",
                "descricao" => "Euro/Real Brasileiro Turismo",
                "created_at" => now(),
                "updated_at" => now(),
            ],
            [
                "codigo" => "EUR-BRLPTAX", 
                "codigo_moeda_base" => "EUR",
                "descricao" => "Euro/Real Brasileiro",
                "created_at" => now(),
                "updated_at" => now(),
            ],
            [
                "codigo" => "CRC-BRL", 
                "codigo_moeda_base" => "CRC",
                "descricao" => "Colón Costarriquenho/Real Brasileiro",
                "created_at" => now(),
                "updated_at" => now(),
            ],
            [
                "codigo" => "RON-BRL", 
                "codigo_moeda_base" => "RON",
                "descricao" => "Leu Romeno/Real Brasileiro",
                "created_at" => now(),
                "updated_at" => now(),
            ],
            [
                "codigo" => "EGP-BRL", 
                "codigo_moeda_base" => "EGP",
                "descricao" => "Libra Egípcia/Real Brasileiro",
                "created_at" => now(),
                "updated_at" => now(),
            ],
            [
                "codigo" => "KES-BRL", 
                "codigo_moeda_base" => "KES",
                "descricao" => "Shilling Queniano/Real Brasileiro",
                "created_at" => now(),
                "updated_at" => now(),
            ],
            [
                "codigo" => "PHP-BRL", 
                "codigo_moeda_base" => "PHP",
                "descricao" => "Peso Filipino/Real Brasileiro",
                "created_at" => now(),
                "updated_at" => now(),
            ],
            [
                "codigo" => "HUF-BRL", 
                "codigo_moeda_base" => "HUF",
                "descricao" => "Florim Húngaro/Real Brasileiro",
                "created_at" => now(),
                "updated_at" => now(),
            ],
            [
                "codigo" => "CZK-BRL", 
                "codigo_moeda_base" => "CZK",
                "descricao" => "Coroa Checa/Real Brasileiro",
                "created_at" => now(),
                "updated_at" => now(),
            ]
        ]);
    }
}
