services:
  app:
    build:
      context: .
      dockerfile: docker/app/Dockerfile
    image: app
    container_name: app
    restart: unless-stopped
    working_dir: /var/www
    volumes:
      - ./:/var/www
    ports:
      - "9000:9000"
    networks:
      - compra_moedas

  mysql:
    image: mysql:8
    container_name: mysql
    restart: unless-stopped
    ports:
      - "3456:3306"
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: compra_moedas
      MYSQL_USER: cm_admin
      MYSQL_PASSWORD: cm_secret
    volumes:
      - dbdata:/var/lib/mysql
      - ./docker/mysql/my.cnf:/etc/mysql/conf.d/my.cnf
    networks:
      - compra_moedas

  nginx:
    image: nginx:alpine
    container_name: nginx
    restart: unless-stopped
    ports:
      - "8910:80"
    volumes:
      - ./:/var/www
      - ./docker/nginx/default.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - app
    networks:
      - compra_moedas

volumes:
  dbdata:

networks:
  compra_moedas:
    driver: bridge
